[package]
name = "ISS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
log = "0.4.14"
serde = "1.0.123"
wasm-bindgen = "0.2.69"
wasm-logger = "0.2.0"
yew = "0.17.4"
